version: "3.8"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - lake

  dremio:
    image: dremio/dremio-oss:latest
    container_name: dremio
    shm_size: "1g"   # penting untuk query planner
    environment:
      DREMIO_MAX_HEAP_MEMORY_SIZE_MB: "2048"
      DREMIO_MAX_DIRECT_MEMORY_SIZE_MB: "2048"
    ports:
      - "9047:9047"   # Web UI
      - "31010:31010" # JDBC/ODBC
    volumes:
      - dremio-data:/opt/dremio/data
    networks:
      - lake

  mc:
    image: minio/mc:latest
    container_name: minio-mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 admin adminadmin123 &&
      mc mb -p local/warehouse || true &&
      mc mb -p local/lakehouse || true &&
      tail -f /dev/null
      "
    networks:
      - lake

  trino-coordinator:
    image: 'trinodb/trino:latest'
    hostname: trino-coordinator
    ports:
      - '8080:8080'
    volumes:
      - ./etc:/etc/trino
    networks:
      - lake

  mariadb:
    image: 'mariadb:latest'
    hostname: mariadb
    ports:
      - '3306:3306'
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
    networks:
      - lake

  hive-metastore:
    image: 'bitsondatadev/hive-metastore:latest'
    hostname: hive-metastore
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: mariadb
    depends_on:
      - mariadb
    networks:
      - lake

volumes:
  minio-data:
  mariadb-data:
  dremio-data:

networks:
  lake:
    driver: bridge

